# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 23:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sb', '0008_auto_20160423_0209'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('song_comment', 'song_comment'), ('gig_comment', 'gig_comment'), ('song_changed', 'song_changed')], max_length=20)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['gig', 'song', '-datetime'],
            },
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Gig name')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('date', models.DateField(verbose_name='Gig date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='gig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sbgig.Gig'),
        ),
        migrations.AddField(
            model_name='comment',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sb.Song'),
        ),
        migrations.AlterIndexTogether(
            name='comment',
            index_together=set([('gig', 'song', 'comment_type', 'datetime'), ('author', 'datetime')]),
        ),
    ]
