# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbgig', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['gig', '-datetime']},
        ),
        migrations.AlterIndexTogether(
            name='comment',
            index_together=set([('gig', 'song', 'datetime'), ('author', 'datetime')]),
        ),
    ]
