# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sbgig', '0001_initial'),
        ('sbsong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sbsong.Song'),
        ),
        migrations.AlterIndexTogether(
            name='comment',
            index_together=set([('author', 'datetime'), ('gig', 'song', 'datetime')]),
        ),
    ]
