# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-01 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbgig', '0003_auto_20160501_0047'),
    ]

    database_operations = [
        migrations.AlterModelTable('Comment', 'sbcomment_comment')
    ]

    state_operations = [
        migrations.DeleteModel('Comment')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
