# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 23:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongPerformer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='songpart',
            name='performer',
        ),
        migrations.AddField(
            model_name='song',
            name='suggested_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='songpart',
            name='notice',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='songperformer',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sb.SongPart'),
        ),
        migrations.AddField(
            model_name='songperformer',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
