# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 23:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0004_auto_20160408_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['name'], 'verbose_name': 'instrument'},
        ),
        migrations.AddField(
            model_name='songcomment',
            name='comment_type',
            field=models.CharField(choices=[('regular', 'regular comment'), ('song_edit', 'song edit')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instrument name'),
        ),
        migrations.AlterField(
            model_name='songcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='songlink',
            name='notice',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='songpart',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='sb.Song'),
        ),
    ]
