# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0007_auto_20160423_0054'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='songcomment',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='songcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='songcomment',
            name='song',
        ),
        migrations.DeleteModel(
            name='SongComment',
        ),
    ]
