# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0009_song_gig'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='staffed',
            field=models.BooleanField(default=False),
        ),
    ]
