# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_myself',
            field=models.TextField(default='', verbose_name='About myself'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('f', 'Female'), ('m', 'Male')], default='m', max_length=1, verbose_name='Gender'),
        ),
    ]
