# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbuser', '0002_auto_20160420_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_change_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_myself',
            field=models.TextField(blank=True, verbose_name='About myself'),
        ),
    ]
