# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 21:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0013_auto_20160425_0043'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sbuser', '0003_auto_20160423_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(blank=True, max_length=150)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sb.Instrument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userplays',
            unique_together=set([('user', 'instrument')]),
        ),
    ]
