# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-01 19:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sbsong', '0005_song_watcher'),
        ('sbgig', '0004_moving_comments'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('song_comment', 'song_comment'), ('gig_comment', 'gig_comment'), ('song_changed', 'song_changed')], max_length=20)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sbgig.Gig')),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sbsong.Song')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.AlterIndexTogether(
            name='comment',
            index_together=set([('gig', 'datetime'), ('song', 'datetime'), ('author', 'datetime')]),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
