# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbsong', '0002_optional_gig'),
    ]

    operations = [
        migrations.AddField(
            model_name='songperformer',
            name='readiness',
            field=models.PositiveSmallIntegerField(choices=[(0, "Haven't seen"), (25, 'Scratched a bit'), (50, 'Peep into the text/chords'), (75, 'Mostly learned'), (100, 'Mastered')], default=0),
        ),
    ]
