# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 23:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sb', '0003_auto_20160408_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongWatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sb.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='songlink',
            unique_together=set([('song', 'link')]),
        ),
        migrations.AlterUniqueTogether(
            name='songperformer',
            unique_together=set([('part', 'performer')]),
        ),
        migrations.AlterUniqueTogether(
            name='userplays',
            unique_together=set([('user', 'instrument')]),
        ),
        migrations.AlterUniqueTogether(
            name='songwatcher',
            unique_together=set([('user', 'song')]),
        ),
    ]
