# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 11:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


def set_readiness(apps, schema_editor):
    Song = apps.get_model('sbsong', 'Song')
    for song in Song.objects.all():
        parts_qs = song.parts.filter(required=True)
        num_parts = parts_qs.count()
        if num_parts == 0:
            new_readiness = 0
        else:
            all_readiness = parts_qs.annotate(
                best_perf=models.Max('songperformer__readiness')
            ).values_list('best_perf', flat=True)
            new_readiness = int(sum(r for r in all_readiness if r) / num_parts)
        if song.readiness == new_readiness:
            continue
        song.readiness = new_readiness
        song.save()


def unset_readiness(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sbsong', '0003_songperformer_readiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='readiness',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),

        migrations.RunPython(set_readiness, unset_readiness),
    ]
