# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 05:43
from datetime import datetime

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sbsong', '0004_song_readiness'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongWatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='sbsong.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_songs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='songwatcher',
            unique_together=set([('song', 'user')]),
        ),
        migrations.RunSQL(
            sql=[("""INSERT INTO sbsong_songwatcher (song_id, user_id, last_seen)
                     SELECT DISTINCT song.id, performer.performer_id, %s
                     FROM sbsong_song AS song
                     JOIN sbsong_songpart AS part
                     ON (song.id = part.song_id)
                     JOIN sbsong_songperformer AS performer
                     ON (performer.part_id = part.id)""", (datetime.utcnow(), ))],
            reverse_sql=""
        )
    ]
