# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 21:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0006_auto_20160420_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='song_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='songcomment',
            index_together=set([('author', 'datetime')]),
        ),
    ]
