# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbgig', '0001_initial'),
        ('sb', '0008_auto_20160423_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='gig',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='sbgig.Gig'),
            preserve_default=False,
        ),
    ]
