# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0010_song_staffed'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='song',
            index_together=set([('gig', 'staffed')]),
        ),
    ]
